services:
  memu-server:
    build:
      context: ..
      args:
        INSTALL_MODE: minimal
        INCLUDE_GPU: false
        INCLUDE_LOCAL_MODELS: false
    ports:
      - "8000:8000"
    env_file: ../.env
    volumes:
      - memu-memory:/app/memory
      - memu-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  memu-memory:
  memu-logs:
