services:
  memu-server:
    build:
      context: ..
      args:
        INSTALL_MODE: server
        INCLUDE_GPU: false
        INCLUDE_LOCAL_MODELS: false
    container_name: memu-server-cpu
    ports:
      - "8000:8000"
    env_file: ../.env
    volumes:
      - memu-memory:/app/memory
      - memu-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - memu-network

volumes:
  memu-memory:
    driver: local
  memu-logs:
    driver: local

networks:
  memu-network:
    driver: bridge
